name: easytrain
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  flutter_riverpod: ^1.0.3
  dartz: ^0.10.1
  intl: ^0.17.0
  table_calendar: ^3.0.4
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700

